apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: monis-torias
data:
  VITE_API_URL: "http://monis-backend.monis-torias.svc.cluster.local:5001/api"
  VITE_FIREBASE_API_KEY: "AIzaSyDExampleKey"  # Actualizar con tu API Key
  VITE_FIREBASE_AUTH_DOMAIN: "proyecto-arqui-2c418.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "proyecto-arqui-2c418"
  VITE_FIREBASE_STORAGE_BUCKET: "proyecto-arqui-2c418.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "123456789"
  VITE_FIREBASE_APP_ID: "1:123456789:web:abcdef"
  VITE_SESSION_PERSISTENCE: "session"
