apiVersion: v1
kind: Service
metadata:
  name: monis-frontend
  namespace: monis-torias
  labels:
    app: monis-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: monis-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
